INSERT INTO dj (id, name) VALUES (1, 'dj1');
INSERT INTO dj (id, name) VALUES (2, 'dj2');

INSERT INTO DJ_SET (id, name,START_DATE,DURATION) VALUES (1,'set1',CURRENT_DATE,120);
INSERT INTO DJ_SET (id, name,START_DATE,DURATION) VALUES (2,'set2',CURRENT_DATE,60);

